---
abstract: 'Wrapper around ps utility on unix'
author:
  - justnoxx
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: System-Process
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  POSIX: 0
version: 0.12
